FROM ubuntu:latest

RUN apt-get update -y && \
    apt-get install -y wget curl mysql-client libmysqlclient-dev bc dos2unix 

WORKDIR /sphinx/

RUN mkdir -p conf

RUN mkdir -p runs

RUN mkdir -p binlog

RUN mkdir -p logs

ADD ./conf/entrypoint.sh ./conf/entrypoint.sh

ADD ./conf/sphinx.conf ./conf/sphinx.conf

RUN chmod +x /sphinx/conf/entrypoint.sh

RUN wget -O sphinx.tar.gz http://sphinxsearch.com/files/sphinx-3.0.3-facc3fb-linux-amd64-glibc2.12.tar.gz && \
    tar -zxf sphinx.tar.gz && \
    rm sphinx.tar.gz && \
    cp sphinx-3.0.3/bin/* /usr/bin/ && \
    rm -rf sphinx-3.0.3